config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'sessions/new'
  root 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'sign' => 'users#new'
  get 'users_list' => 'users#users_list'
  get 'search' => 'users#search'
  get 'login' => 'sessions#new'
  get 'follow_action' => 'users#follow_action'
  get 'unfollow_action' => 'users#unfollow_action'
  get 'forgot_password' => 'users#forgot_password'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :posts, only: [:create, :destroy]
  resources :reposts, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :users do
    member do
      get :followings, :followers
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\a-z+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 250 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 8 }, on: :create
  validates :password_confirmation, presence: true
  has_many :posts, dependent: :destroy
  has_many :reposts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, :through => :likes, :source => :post

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST:
                 BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def feed
    followings_posts + followings_reposts
  end

  def followings_posts
    followings_ids = followings.map(&:id_usuario)
    Post.where('user_id IN (?) OR user_id = ?', followings_ids, id)
  end

  def followings_reposts
    followings_ids = followings.map(&:id_usuario)
    Repost.where('user_id IN (?) OR user_id = ?', followings_ids, id)
  end

  has_many :followers
  has_many :followings

  def following?(other_user)
    followings.any? { |following| following.id_usuario == other_user.id }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Followable

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @reposts = @user.reposts
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:sucess] = 'Bienvenido al foro'
      redirect_to @user
    else
      render 'new'
    end
  end

  def all
    @user = User.all
  end

  def users_list
    all
  end

  def search
    all
  end

  def forgot_password
    @user = User.find_by_email(params[:email])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = 'user.png'
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/users/_follow_form.html.erb
<% if current_user?(@user) %>
  <%= link_to "Editar perfil", edit_user_path(id: @user), class: "btn btn-lg btn-primary" %>
<% else %>
  <% if current_user.following?(@user) %>
    <%= link_to "Dejar de Seguir", unfollow_action_path(id: @user), class: "btn btn-lg btn-danger" %>
  <% else %>
    <%= link_to "Seguir", follow_action_path(id: @user), class: "btn btn-lg btn-primary" %>
  <% end %>
<% end %>

app/views/users/_follow_stats.html.erb
<ul class="stats">
  <li class="stat">
    <%= link_to(followers_user_path(@user)) do %>
      <strong><%= @user.followers.count %></strong> Seguidores
    <% end %>
  </li>

  <li class="stat">
    <%= link_to(followings_user_path(@user)) do %>
      <strong><%= @user.followings.count %></strong> Siguiendo
    <% end %>
  </li>
</ul>

app/views/users/_form.html.erb
<%= form_for :user do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li class="user-info">
  <%= link_to(user) do %>
    <span><%= user.name %></span>
    <%= gravatar_for user %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render "shared/error_messages_user" %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <div class = "field">
        <%= gravatar_for @user %>
        <%= f.label :image, 'Change photo' %>
        <%= f.file_field :image %>
      </div>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/follow_action.html.erb
<%
  user_logueado = current_user
  user_a_seguir = User.find(params[:id])
  Following.create!(name: user_a_seguir.name,id_usuario: user_a_seguir.id, user_id: user_logueado.id)
  Follower.create!(name: user_logueado.name, id_usuario: user_logueado.id, user_id: user_a_seguir.id)
%>
<p>Ahora sigues a: <%= user_a_seguir.name %>!</p>
<p class="name"> <%= link_to "Volver al perfil", user_path(id: user_a_seguir), class: "btn btn-lg btn-primary" %></p>

app/views/users/followers.html.erb
<p>Lista de usuarios del sistema</p>
<p>Seleccione un usuario para ver sus datos, seguidores y siguiendos</p>
  <% @user.each do |user|  %>
    <p class="name"><%= link_to user.name, follower_for_user_path(:id => user.id), class: "btn btn-lg btn-primary" %>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password digest</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "Nombre Completo" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "Correo electrónico" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "Contraseña" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmación" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Crear mi cuenta", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/search.html.erb
<p> Ingreso: <%= input = CGI.parse(URI.parse(request.original_url()).query)["q"][0] %></p>
<p>Se encontraron los siguientes usuarios: </p>
<% cant = 0 %>
<% @user.each do |user| %>
  <% if input.in? user.name %>
    <p class="name"><%= link_to user.name, user_path(:id => user.id), class: "btn btn-lg btn-primary" %>
    <% cant += 1 %>
  <% end %>
<% end %>
<p> ----------------------------------------------</p>
<p> Cantidad de usuarios encontrados: <%= cant %> </p>
<p> ----------------------------------------------</p>
<p class="name"> <%= link_to "Volver a inicio", home_path(), class: "btn btn-lg btn-primary" %></p>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <div class="username">
        <h1> <%= "@#{@user.name}" %> </h1>
        <%= render 'follow_form' if logged_in? %>
      </div>
    </section>
    <section>
      <%= render 'follow_stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @posts.any? || @reposts.any? %>
      <h3>Posts (<%= @posts.count + @reposts.count %>)</h3>
      <ul class="posts">
        <%= render (@posts + @reposts).sort_by{|p| p.created_at}.reverse %>
      </ul>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <div class="username">
        <h1> <%= link_to "@#{@user.name}", @user %> </h1>
        <%= render 'follow_form' if logged_in? %>
      </div>
    </section>
    <section>
      <%= render 'follow_stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users-follow">
        <%= render @users %>
      </ul>
    <% end %>
  </div>
</div>

app/views/users/unfollow_action.html.erb
<%
  id_log = current_user.id
  user_logueado = User.find(id_log)
  user_a_dejar_de_seguir = User.find(params[:id])
%>

<%
   user_a_dejar_de_seguir.followers.each do |follower|
     if follower.name == user_logueado.name
       follower.destroy
       break
     end
   end
%>

<%
  user_logueado.followings.each do |following|
    if following.name == user_a_dejar_de_seguir.name
      following.destroy
      break
    end
  end
%>

<p> Ya no sigues a <%= user_a_dejar_de_seguir.name %>!</p>
<p class="name"> <%= link_to "Volver a inicio", home_path(), class: "btn btn-lg btn-primary" %></p>

app/views/users/users_list.html.erb
<p>Lista de usuarios del sistema</p>
<p>Seleccione un usuario para ver sus datos, seguidores y siguiendos</p>
  <% @user.each do |user|  %>
    <p class="name"><%= link_to user.name, user_path(:id => user.id), class: "btn btn-lg btn-primary" %>
<% end %>