config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'sessions/new'
  root 'static_pages#home'
  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'sign' => 'users#new'
  get 'users_list' => 'users#users_list'
  get 'search' => 'users#search'
  get 'login' => 'sessions#new'
  get 'follow_action' => 'users#follow_action'
  get 'unfollow_action' => 'users#unfollow_action'
  get 'forgot_password' => 'users#forgot_password'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :posts, only: [:create, :destroy]
  resources :reposts, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :users do
    member do
      get :followings, :followers
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :user
end

app/models/following.rb
class Following < ActiveRecord::Base
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  has_many :reposts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liking_users, :through => :likes, :source => :user
end

app/models/repost.rb
class Repost < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :post_id, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\a-z+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 250 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 8 }, on: :create
  validates :password_confirmation, presence: true
  has_many :posts, dependent: :destroy
  has_many :reposts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, :through => :likes, :source => :post

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST:
                 BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def feed
    followings_posts + followings_reposts
  end

  def followings_posts
    followings_ids = followings.map(&:id_usuario)
    Post.where('user_id IN (?) OR user_id = ?', followings_ids, id)
  end

  def followings_reposts
    followings_ids = followings.map(&:id_usuario)
    Repost.where('user_id IN (?) OR user_id = ?', followings_ids, id)
  end

  has_many :followers
  has_many :followings

  def following?(other_user)
    followings.any? { |following| following.id_usuario == other_user.id }
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def create
    @repost = current_user.likes.build(like_params)
    if @repost.save
      flash[:success] = "Post liked"
      redirect_to request.referrer
    else
      render 'static_pages/home'
    end
  end

  def destroy
    Like.destroy(params[:id])
    flash[:success] = "Post unliked"
    redirect_to request.referrer
  end

  private

  def like_params
    params.permit(:post_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post creado!"
      redirect_to request.referrer
    else
      render 'static_pages/home'
    end
  end

  def destroy
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/reposts_controller.rb
class RepostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def create
    @repost = current_user.reposts.build(repost_params)
    if @repost.save
      flash[:success] = "Repost creado!"
      redirect_to request.referrer
    else
      render 'static_pages/home'
    end
  end

  def destroy
  end

  private

  def repost_params
    params.permit(:post_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Followable

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @reposts = @user.reposts
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:sucess] = 'Bienvenido al foro'
      redirect_to @user
    else
      render 'new'
    end
  end

  def all
    @user = User.all
  end

  def users_list
    all
  end

  def search
    all
  end

  def forgot_password
    @user = User.find_by_email(params[:email])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Ruby on Rails Proyecto - Grupo 15'
    if page_title.blank?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reposts_helper.rb
module RepostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user&.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user?(user)
    user && user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    forget current_user
    session.delete(:user_id)
    @current_user = nil
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = 'user.png'
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Ruby on Rails Proyect
    by Group 15
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logo.png', height: 30, id: 'logo', class: 'd-inline-block align-top'), root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <!-- Search bar -->
        <li class="search-bar">
          <%= render 'layouts/search_bar' %>
        </li>

        <!-- Sign up and log in -->
        <% if logged_in? %>
          <li>
            <%= link_to current_user do %>
              <div class="header-user">
                <%= "@#{current_user.name}" %>
              </div>
            <% end %>
          </li>
          <li>
            <%= link_to logout_path, method: "delete" do %>
              <span class="glyphicon glyphicon-log-out"></span> Log out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to sign_path do %>
              <span class="glyphicon glyphicon-user"></span> Sign Up
            <% end %>
          </li>
          <li>
            <%= render 'layouts/login' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_login.html.erb
<li class="dropdown">
  <a href='login' class="dropdown-toggle" data-toggle="dropdown">
    <span class="glyphicon glyphicon-log-in"></span> Login <b class="caret"></b>
  </a>
  <ul class="dropdown-menu", id="menuLogin">
    <div class="col-xs-12 col-md-offset">
      <%= form_for(:session, url: login_path) do |f| %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control'%>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :remember_me, class: "checkbox inline" do %>
          <%= f.check_box :remember_me %>
          <span>Remember me</span>
        <% end %>

        <%= f.submit "Log in", class: "btn btn-primary" %>
      <% end %>

      <li class="divider"></li>
      <li><%= link_to "New around here? Sign up", sign_path %></li>
      <li><%= link_to "Forgot password?", forgot_password_path %></li>
    </div>
  </ul>
</li>

app/views/layouts/_search_bar.html.erb
<%= form_tag("/search", method: "get", class: 'navbar-form') do %>
    <div class="input-group">
      <%= text_field_tag :q, params[:q], placeholder: "Buscar un usuario", class: "form-control" %>
      <div class="input-group-btn">
        <%= button_tag(type: 'submit', class: 'btn btn-default') do %>
          <i class="glyphicon glyphicon-search"></i>
        <% end %>
      </div>
    </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="main">
  <div class="container">
    <h1>TP TDL</h1>
    <p> Grupo 15.</p>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      El formulario contiene <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_user.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      El formulario contiene <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.try(:any?) %>
  <ul class="posts">
    <%= render @feed_items.sort_by{|p| p.created_at}.reverse %>
  </ul>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: 'Crear nuevo post...', rows: 4, class: 'form-control' %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>